

 @echo off
echo INSTALLING nodemon ...
call npm install -g nodemon
echo INSTALLING discord.js ...
call npm install -g discord.js
echo INSTALLING firebase ...
call npm install -g firebase
echo INSTALLING cron ...
call npm install -g cron
echo INSTALLING PM2 ...
call npm install -g pm2
echo INSTALLING moment-timezone ...
call npm install moment-timezone --save
cd %SETUP_DIR%
echo DONE!